/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PtBrIndexRouteImport } from './routes/pt-br/index'
import { Route as PtBrAboutRouteImport } from './routes/pt-br/about'
import { Route as PtBrArchitectureRouteImport } from './routes/pt-br/architecture'
import { Route as PtBrBlogRouteImport } from './routes/pt-br/blog'
import { Route as PtBrChangelogRouteImport } from './routes/pt-br/changelog'
import { Route as PtBrLearningRouteImport } from './routes/pt-br/learning'
import { Route as PtBrProjectsRouteImport } from './routes/pt-br/projects'
import { Route as PtBrSearchRouteImport } from './routes/pt-br/search'
import { Route as PtBrUsesRouteImport } from './routes/pt-br/uses'
import { Route as PtBrBlogIndexRouteImport } from './routes/pt-br/blog.index'
import { Route as PtBrBlogSlugRouteImport } from './routes/pt-br/blog.$slug'
import { Route as PtBrProjectsIndexRouteImport } from './routes/pt-br/projects.index'
import { Route as PtBrProjectsSlugRouteImport } from './routes/pt-br/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PtBrIndexRoute = PtBrIndexRouteImport.update({
  id: '/pt-br/',
  path: '/pt-br/',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrAboutRoute = PtBrAboutRouteImport.update({
  id: '/pt-br/about',
  path: '/pt-br/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrArchitectureRoute = PtBrArchitectureRouteImport.update({
  id: '/pt-br/architecture',
  path: '/pt-br/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrBlogRoute = PtBrBlogRouteImport.update({
  id: '/pt-br/blog',
  path: '/pt-br/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrChangelogRoute = PtBrChangelogRouteImport.update({
  id: '/pt-br/changelog',
  path: '/pt-br/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrLearningRoute = PtBrLearningRouteImport.update({
  id: '/pt-br/learning',
  path: '/pt-br/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrProjectsRoute = PtBrProjectsRouteImport.update({
  id: '/pt-br/projects',
  path: '/pt-br/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrSearchRoute = PtBrSearchRouteImport.update({
  id: '/pt-br/search',
  path: '/pt-br/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrUsesRoute = PtBrUsesRouteImport.update({
  id: '/pt-br/uses',
  path: '/pt-br/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrBlogIndexRoute = PtBrBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtBrBlogRoute,
} as any)
const PtBrBlogSlugRoute = PtBrBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PtBrBlogRoute,
} as any)
const PtBrProjectsIndexRoute = PtBrProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtBrProjectsRoute,
} as any)
const PtBrProjectsSlugRoute = PtBrProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PtBrProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/learning': typeof LearningRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/pt-br/about': typeof PtBrAboutRoute
  '/pt-br/architecture': typeof PtBrArchitectureRoute
  '/pt-br/blog': typeof PtBrBlogRouteWithChildren
  '/pt-br/changelog': typeof PtBrChangelogRoute
  '/pt-br/learning': typeof PtBrLearningRoute
  '/pt-br/projects': typeof PtBrProjectsRouteWithChildren
  '/pt-br/search': typeof PtBrSearchRoute
  '/pt-br/uses': typeof PtBrUsesRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/pt-br/': typeof PtBrIndexRoute
  '/pt-br/blog/$slug': typeof PtBrBlogSlugRoute
  '/pt-br/projects/$slug': typeof PtBrProjectsSlugRoute
  '/pt-br/blog/': typeof PtBrBlogIndexRoute
  '/pt-br/projects/': typeof PtBrProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/changelog': typeof ChangelogRoute
  '/learning': typeof LearningRoute
  '/search': typeof SearchRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/pt-br/about': typeof PtBrAboutRoute
  '/pt-br/architecture': typeof PtBrArchitectureRoute
  '/pt-br/changelog': typeof PtBrChangelogRoute
  '/pt-br/learning': typeof PtBrLearningRoute
  '/pt-br/search': typeof PtBrSearchRoute
  '/pt-br/uses': typeof PtBrUsesRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/pt-br': typeof PtBrIndexRoute
  '/pt-br/blog/$slug': typeof PtBrBlogSlugRoute
  '/pt-br/projects/$slug': typeof PtBrProjectsSlugRoute
  '/pt-br/blog': typeof PtBrBlogIndexRoute
  '/pt-br/projects': typeof PtBrProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/learning': typeof LearningRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/search': typeof SearchRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/pt-br/about': typeof PtBrAboutRoute
  '/pt-br/architecture': typeof PtBrArchitectureRoute
  '/pt-br/blog': typeof PtBrBlogRouteWithChildren
  '/pt-br/changelog': typeof PtBrChangelogRoute
  '/pt-br/learning': typeof PtBrLearningRoute
  '/pt-br/projects': typeof PtBrProjectsRouteWithChildren
  '/pt-br/search': typeof PtBrSearchRoute
  '/pt-br/uses': typeof PtBrUsesRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/pt-br/': typeof PtBrIndexRoute
  '/pt-br/blog/$slug': typeof PtBrBlogSlugRoute
  '/pt-br/projects/$slug': typeof PtBrProjectsSlugRoute
  '/pt-br/blog/': typeof PtBrBlogIndexRoute
  '/pt-br/projects/': typeof PtBrProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/blog'
    | '/changelog'
    | '/learning'
    | '/projects'
    | '/search'
    | '/uses'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/pt-br/about'
    | '/pt-br/architecture'
    | '/pt-br/blog'
    | '/pt-br/changelog'
    | '/pt-br/learning'
    | '/pt-br/projects'
    | '/pt-br/search'
    | '/pt-br/uses'
    | '/blog/'
    | '/projects/'
    | '/pt-br/'
    | '/pt-br/blog/$slug'
    | '/pt-br/projects/$slug'
    | '/pt-br/blog/'
    | '/pt-br/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architecture'
    | '/changelog'
    | '/learning'
    | '/search'
    | '/uses'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/pt-br/about'
    | '/pt-br/architecture'
    | '/pt-br/changelog'
    | '/pt-br/learning'
    | '/pt-br/search'
    | '/pt-br/uses'
    | '/blog'
    | '/projects'
    | '/pt-br'
    | '/pt-br/blog/$slug'
    | '/pt-br/projects/$slug'
    | '/pt-br/blog'
    | '/pt-br/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/blog'
    | '/changelog'
    | '/learning'
    | '/projects'
    | '/search'
    | '/uses'
    | '/blog/$slug'
    | '/projects/$slug'
    | '/pt-br/about'
    | '/pt-br/architecture'
    | '/pt-br/blog'
    | '/pt-br/changelog'
    | '/pt-br/learning'
    | '/pt-br/projects'
    | '/pt-br/search'
    | '/pt-br/uses'
    | '/blog/'
    | '/projects/'
    | '/pt-br/'
    | '/pt-br/blog/$slug'
    | '/pt-br/projects/$slug'
    | '/pt-br/blog/'
    | '/pt-br/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  LearningRoute: typeof LearningRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SearchRoute: typeof SearchRoute
  UsesRoute: typeof UsesRoute
  PtBrAboutRoute: typeof PtBrAboutRoute
  PtBrArchitectureRoute: typeof PtBrArchitectureRoute
  PtBrBlogRoute: typeof PtBrBlogRouteWithChildren
  PtBrChangelogRoute: typeof PtBrChangelogRoute
  PtBrLearningRoute: typeof PtBrLearningRoute
  PtBrProjectsRoute: typeof PtBrProjectsRouteWithChildren
  PtBrSearchRoute: typeof PtBrSearchRoute
  PtBrUsesRoute: typeof PtBrUsesRoute
  PtBrIndexRoute: typeof PtBrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/pt-br/': {
      id: '/pt-br/'
      path: '/pt-br'
      fullPath: '/pt-br/'
      preLoaderRoute: typeof PtBrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/about': {
      id: '/pt-br/about'
      path: '/pt-br/about'
      fullPath: '/pt-br/about'
      preLoaderRoute: typeof PtBrAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/architecture': {
      id: '/pt-br/architecture'
      path: '/pt-br/architecture'
      fullPath: '/pt-br/architecture'
      preLoaderRoute: typeof PtBrArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/blog': {
      id: '/pt-br/blog'
      path: '/pt-br/blog'
      fullPath: '/pt-br/blog'
      preLoaderRoute: typeof PtBrBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/changelog': {
      id: '/pt-br/changelog'
      path: '/pt-br/changelog'
      fullPath: '/pt-br/changelog'
      preLoaderRoute: typeof PtBrChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/learning': {
      id: '/pt-br/learning'
      path: '/pt-br/learning'
      fullPath: '/pt-br/learning'
      preLoaderRoute: typeof PtBrLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/projects': {
      id: '/pt-br/projects'
      path: '/pt-br/projects'
      fullPath: '/pt-br/projects'
      preLoaderRoute: typeof PtBrProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/search': {
      id: '/pt-br/search'
      path: '/pt-br/search'
      fullPath: '/pt-br/search'
      preLoaderRoute: typeof PtBrSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/uses': {
      id: '/pt-br/uses'
      path: '/pt-br/uses'
      fullPath: '/pt-br/uses'
      preLoaderRoute: typeof PtBrUsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/blog/': {
      id: '/pt-br/blog/'
      path: '/'
      fullPath: '/pt-br/blog/'
      preLoaderRoute: typeof PtBrBlogIndexRouteImport
      parentRoute: typeof PtBrBlogRoute
    }
    '/pt-br/blog/$slug': {
      id: '/pt-br/blog/$slug'
      path: '/$slug'
      fullPath: '/pt-br/blog/$slug'
      preLoaderRoute: typeof PtBrBlogSlugRouteImport
      parentRoute: typeof PtBrBlogRoute
    }
    '/pt-br/projects/': {
      id: '/pt-br/projects/'
      path: '/'
      fullPath: '/pt-br/projects/'
      preLoaderRoute: typeof PtBrProjectsIndexRouteImport
      parentRoute: typeof PtBrProjectsRoute
    }
    '/pt-br/projects/$slug': {
      id: '/pt-br/projects/$slug'
      path: '/$slug'
      fullPath: '/pt-br/projects/$slug'
      preLoaderRoute: typeof PtBrProjectsSlugRouteImport
      parentRoute: typeof PtBrProjectsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface PtBrBlogRouteChildren {
  PtBrBlogSlugRoute: typeof PtBrBlogSlugRoute
  PtBrBlogIndexRoute: typeof PtBrBlogIndexRoute
}

const PtBrBlogRouteChildren: PtBrBlogRouteChildren = {
  PtBrBlogSlugRoute: PtBrBlogSlugRoute,
  PtBrBlogIndexRoute: PtBrBlogIndexRoute,
}

const PtBrBlogRouteWithChildren = PtBrBlogRoute._addFileChildren(
  PtBrBlogRouteChildren,
)

interface PtBrProjectsRouteChildren {
  PtBrProjectsSlugRoute: typeof PtBrProjectsSlugRoute
  PtBrProjectsIndexRoute: typeof PtBrProjectsIndexRoute
}

const PtBrProjectsRouteChildren: PtBrProjectsRouteChildren = {
  PtBrProjectsSlugRoute: PtBrProjectsSlugRoute,
  PtBrProjectsIndexRoute: PtBrProjectsIndexRoute,
}

const PtBrProjectsRouteWithChildren = PtBrProjectsRoute._addFileChildren(
  PtBrProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  LearningRoute: LearningRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SearchRoute: SearchRoute,
  UsesRoute: UsesRoute,
  PtBrAboutRoute: PtBrAboutRoute,
  PtBrArchitectureRoute: PtBrArchitectureRoute,
  PtBrBlogRoute: PtBrBlogRouteWithChildren,
  PtBrChangelogRoute: PtBrChangelogRoute,
  PtBrLearningRoute: PtBrLearningRoute,
  PtBrProjectsRoute: PtBrProjectsRouteWithChildren,
  PtBrSearchRoute: PtBrSearchRoute,
  PtBrUsesRoute: PtBrUsesRoute,
  PtBrIndexRoute: PtBrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
